### ISSUE TITLE
greyscale output on C.H.I.P.

### ISSUE THREAD

**Issue by combs** [chidea/FBpyGIF#10]
This is very cool! I am trying it out on a C.H.I.P. It is outputting the GIFs in black-and-white. `-ct` outputs vertical black and white stripes. Suggestions?

**Comment by combs** [comment]
(I am displaying on composite output)

**Comment by combs** [comment]
Ahh, I think its framebuffer is rgb565:
EDIT, this is wrong, not actually from the CHIP device tree or w/e:

```
chosen {
    framebuffer0: framebuffer@1d385000 {
        compatible = "simple-framebuffer";
        reg = <0x1d385000 (1600 * 1200 * 2)>;
        width = <1600>;
        height = <1200>;
        stride = <(1600 * 2)>;
        format = "r5g6b5";
        clocks = <&ahb_gates 36>, <&ahb_gates 43>, <&ahb_gates 44>;
        display = <&lcdc0>;
    };
    stdout-path = "display0";
};
```

**Comment by chidea** [comment]
Oh, thanks for that information. I don't have a C.H.I.P. but funded an onion omega..
So I can't really test for your system but could make it compatible with this information.
I'll try some work with it and post about it later.

**Comment by combs** [comment]
Oh wow, thank you! 

I did notice that pillow recently added some rgb565 functions:
https://github.com/rhempel/ev3dev-lang-python/pull/26/commits/7fc5fdad163bef982b7fa1e5e0a37ad83a691e93
got stuck integrating it with the mmap goodness...

**Comment by combs** [comment]
oh I guess that's not pillow, but maybe it helps nonetheless...

**Comment by chidea** [comment]
Would you check if 27b871e3a5998c19f7d4b8f6ff1bb38246c3a614 works?

**Comment by combs** [comment]
sorry for my delay in response. Very much appreciate your coding this. It runs without error but still produces the same output (as does latest commit). I will poke around and see if I can figure anything out.

**Comment by combs** [comment]
ready_fb is returning 24

```
def fill_scr(r,g,b):
  mm, w, h, bpp = ready_fb() 
  print(bpp)
...
```

```
chip@chip:~/FBpyGIF$ python3 main.py -ct
24
Press Ctrl+C to stop playing 
Color testing mode
24
```

**Comment by combs** [comment]
if I force it to 16bpp (the code seems to assume 24) by updating all `ready_fb()` to `ready_fb(16)`, it does this:

```
chip@chip:~/FBpyGIF$ python3 main.py -ct
16
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    fb.black_scr()
  File "/home/chip/FBpyGIF/fb.py", line 238, in black_scr
    fill_scr(0,0,0)
  File "/home/chip/FBpyGIF/fb.py", line 217, in fill_scr
    seed = struct.pack('BB', r>>3, g>>2, b>>3)
struct.error: pack expected 2 items for packing (got 3)
```

**Comment by combs** [comment]
It sounds like Python doesn't have good bitwise struct.pack. I am getting somewhere with this--the colors aren't right (ff0000 is magenta, 00ff00 looks great, 0000ff is dark green) but they are colors! once this is right I'll try the imagemagick call next...

```
  elif bpp == 16: # for C.H.I.P.
    seed = struct.pack('BB', ( r & 0B11111000 )  | ( g >> 5 ) , ( ( g & 0B00000111 ) << 5 ) | ( b>>3 ) )

```

**Comment by combs** [comment]
ok, after poking around for a while I am fairly sure that packing logic is right. 

```
    seed = struct.pack('BB', ( r & 0B11111000 )  | ( g >> 5 ) , ( ( g & 7 ) << 5 ) | ( b >> 3 ) )
```

and another interesting tidbit, it is only filling 2/3 of the screen, so it is getting misaligned somewhere en route to the screen. hmm...

**Comment by combs** [comment]
ah, it's getting double-converted--once in `fill_scr` and again in `show_img`. but the logic used by `show_img` in `RGB_to_565` may not be quite right.

**Comment by chidea** [comment]
`fill_scr` builds up some color bytes with `struct.pack` so it doesn't need any conversion while `show_img` converts RGB888 to 565 because PILlow doesn't support direct conversion of it.
I'll try to fix RGB565 conversion function then..

**Comment by chidea** [comment]
Please check 030fe5922205076204d71c166b93e13f129b88f6 out.

```
    seed = struct.pack('H', (r<<11 | g<<5 | b))
```

**Comment by chidea** [comment]
There was no option to produce 2bytes with `.tobytes()` function in PILlow..
So I decided to produce bytes manually.
Hope 65263cd1f2c6f8c58992c37e2da3701a12865a41 works on C.H.I.P..

**Comment by chidea** [comment]
During making it to support Odroid C2, found the same issue.
It's fixed on 5d7c1f8ee1c360247c01458712f5a73a6fab55bc , but since this device uses 32 bits per pixel, I'm not so sure if it'll work on C.H.I.P. too.
It'll greatly help me if you post `vi` and `fi` values in `ready_fb` function. They seems to very different on every devices, especially on single board PCs.
042cc630df0a5119ad19d3870c3ff065910e7673 got `report_fb` function for your convenience.

**Comment by combs** [comment]
Apologies for slow response. ddc5f78cafa634b3ba9678c27ee5b00ac581a427 still has greyscale output. Here is `report_fb` output:

```
[720, 480, 720, 480, 0, 0, 24, 0, 16, 8, 0, 8, 8, 0, 0, 8, 0, 0, 0, 0, 0, 0, 4294967295, 4294967295, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
(b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', 1536163840, 1382400, 0, 0, 2, 1, 1, 0, 2880, 0, 0, 0, 0, 0, 0)
```

**Comment by combs** [comment]
wow, ok, so that is totally different than what I had shared earlier. Sorry. huh, do those bitfields look right?

```

    __u32 bits_per_pixel;       /* guess what           */
    __u32 grayscale;        /* != 0 Graylevels instead of colors */

    struct fb_bitfield red;     /* bitfield in fb mem if true color, */
    struct fb_bitfield green;   /* else only length is significant */
    struct fb_bitfield blue;
    struct fb_bitfield transp;  /* transparency         */  

```

**Comment by combs** [comment]
I finally got it working!!

By forcing the fb to initialize at 32bpp inside `ready_fb`:

```
    # vi[6] = _bpp # 24 bit = BGR 888 mode
    vi[6] = 32 
```

I am sorry about the rgb565 red herring. I hope that it is useful for another platform.

**Comment by combs** [comment]
Here is a CHIP displaying a gif from headlikeanorange.tumblr.com:
https://dl.dropboxusercontent.com/u/123410/2016-10-11%2002.19.13.mp4
(Don't worry about the black flashes, I believe it is caused by transparency/color table in the gif. Should be post-processable.)

Thank you very much for your help.

**Comment by chidea** [comment]
Calling `ready_fb(32)` before other action will do the same work then.
Hmm.. it seems C.H.I.P. has 24bit BGR888 mode frame buffer as default which is also the raspberry pi has.
Wonder what makes it fall into greyscale mode..
Thanks for sharing typo error note and test results!

**Comment by chidea** [comment]
FYI,  ea6e95cd3cda3e57f6e74013023e91033226867c got `sudo python3 main.py -bpp 32 ...` flag which will do the same work.
