### ISSUE TITLE
overlapping display of gif

### ISSUE THREAD

**Issue by alexylem** [chidea/FBpyGIF#12]
Thanks for sharing this nice tool.
I've tested it on a Raspberry Pi 3 on Raspbian Jessie Lite with a 5" HDMI screen.

```shell
$> python3 main.py -fb 0 ezgif-2-7fe66daa6e.gif
```

this GIF (wide):
![ezgif com-gif-maker 9](https://cloud.githubusercontent.com/assets/11017174/23774264/3a391cb4-0523-11e7-8a00-a6bf7e8f878c.gif)

renders like this (cloned and overlapping):
![cat](https://cloud.githubusercontent.com/assets/11017174/23774267/3e4bb91a-0523-11e7-9f6c-50c0686c4702.gif)

I've tried playing with `-w` flag with no success.
Any idea?
Thanks!

**Comment by chidea** [comment]
It probably is recognizing wrong size of screen or wrong bits per pixel.
Would you report your status of fb?

`python3 -c "import fb; fb.report_fb()"`

**Comment by alexylem** [comment]
Thanks for helping me!
```shell
[800, 480, 800, 480, 0, 0, 16, 0, 11, 5, 0, 5, 6, 0, 0, 5, 0, 16, 0, 0, 0, 0, 4294967295, 4294967295, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
(b'B', b'C', b'M', b'2', b'7', b'0', b'8', b' ', b'F', b'B', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', b'\x00', 1035202560, 768000, 0, 0, 2, 1, 1, 0, 1600, 0, 0, 0, 0, 0, 0)
```
If I try:
```shell
python3 main.py -fb 0 -w 0,0,800,480 ../ezgif-2-7fe66daa6e.gif 
```
It gives the same overlapping result.

**Comment by chidea** [comment]
My guess is that your display is using different physical resolution rather than frame buffer setting.
Would you check if the specification of your display has the same resolution as 800x480?

**Comment by alexylem** [comment]
It is this one:
http://amzn.eu/9XNEr2j
Resolution is 800x480 with HDMI connector
Other programs such as `mplayer` display correctly in the framebuffer
I only set in /boot/config.txt to make it work (as per constructor manual):
```shell
max_usb_current=1
hdmi_group=2
hdmi_mode=1 
hdmi_mode=87
hdmi_cvt 800 480 60 6 0 0 0
```
Would it help if I try normal image with `fbi`?

**Comment by alexylem** [comment]
I was randomly testing other values for `-bpp` and found that 24 works 😄 

```shell
python3 main.py -fb 0 -bpp 24 ../ezgif-2-7fe66daa6e.gif 
```

Hope this will help others...

**Comment by chidea** [comment]
Thanks for testing!
