### ISSUE TITLE
Feature-Request: clear screen/fb

### ISSUE THREAD

**Issue by ozett** [chidea/FBpyGIF#2]
hi, 
i cloned repository today. very cool improvements...

i used the call of fb.py to clear the frambuffer after my experiments. was a cool function.
now fb.py -> main.py default without cmd-args to color-mode.

may you want to consider to code a -switch to clear the framebuffer like before?

great thing... since the beginning i am using it on a regular basis as picture-fame :smile:

**Comment by chidea** [comment]
Sorry, I was on a deadline..
It can be controversial because there are two clearing on start and exit.
Is `-nc` or `--no-clear` to not clearing on both start and exit seems Okay?
Or are they need to be separated?

**Comment by chidea** [comment]
bc022653e9fd4d0f6c8288ec88bfaeb6e9fd5d26 offers `-nc` to skip clearing on both cases.
Please try and feel free to send any issues back.

**Comment by ozett** [comment]
this -nc is cool. so i can skip clearing.
but there is at the moment no option to let "fbpy" do only a clearing? or is there?

that would be also cool, because i used it before to clear scrablemd screens after experimenting with the framebuffer.
so -clear would be cool...

(thanks for "invititiation" for feedback :smile: , i miss a major feature, but make anther issue/reques :smiley: )

**Comment by chidea** [comment]
That's an easy work. 6bffdb9e1b665a292ee2ed4c55ba8b167ff50db0 will allow `-c` and `--clear` which fills with black by default, or with a color given as RGB code as argument and doesn't do any other work but quit.

**Comment by ozett** [comment]
:+1: 
and :+1:  for color-option while clearing....
