### ISSUE TITLE
files in a directory was load random

### ISSUE THREAD

**Issue by xlla** [chidea/FBpyGIF#27]
I have prepared a batch bmp files, ie 0001.bmp ~0120.bmp.
but those files was displayed in random sequence.
I have to add a sorted function in /usr/lib/python3.7/site-packages/FBpyGIF/path.py
now it works as expect.

**Comment by chidea** [comment]
Thanks for sharing your experiences.
I'll consider it to have a legit test code for that case in next Rust version.
