### ISSUE TITLE
without cmd-line ....better to show help?

### ISSUE THREAD

**Issue by ozett** [chidea/FBpyGIF#3]
i was irritated because calling main.py without cmd-line args give no help, 
but starts the color-mode.
wouldn it be more usual for oritentation to throw out help, if called with no args :question: 

and besides: is this i typo-error in the help? shouldn it be the other way round?
"no-loop" make looping forever :question:  

`-nl, --no-loop        Make entire playlist loop forever.`

**Comment by chidea** [comment]
Yes that's a mistype. Thanks for noticing.
Okay, I'll add `-ct` or `--color-test` option to do that and print help instead on no arguments.

**Comment by chidea** [comment]
bc022653e9fd4d0f6c8288ec88bfaeb6e9fd5d26
