### ISSUE TITLE
KeyError: 'duration'

### ISSUE THREAD

**Issue by ozett** [chidea/FBpyGIF#4]
i put my path from the old version (versioning...) in, 
everthing was the same, and got this error:

<img width="391" alt="fbpy2" src="https://cloud.githubusercontent.com/assets/5937811/17068963/3c429ab4-5054-11e6-9f5c-d1b9dcd81b1d.png">

**Comment by chidea** [comment]
I think there's a gif file with a cut which has no duration information specified.
I'll use 1 second as default. Please try again after this update.

**Comment by chidea** [comment]
Does bc022653e9fd4d0f6c8288ec88bfaeb6e9fd5d26 fix this?

**Comment by ozett** [comment]
sorry for the delay, going to holidays tommorrow..
ill check in next minutes... and report back

**Comment by ozett** [comment]
its running. i had to look twice to see that i must use -gd (global delay) to set the timeout for all image-changing. 
if i ommit any time-option, the images flipped very fast. maybe there should be a fix default for timeout?

i could maybe a little bit easier to have a non-explixit -switch for a default overall global-timeout. this global waiting time could be modified with explicit -switches for both picture types: animation or static. 
if not given, than the global-timeout is valid for every picture type. 

but at least, :cool: 
i have it running, it looks good, an i will see if any error pops up on my 600 pics in the picture frame..can take some time...

**Comment by ozett** [comment]
it died, somehow. silently.... after 5 hrs running fine ...
if i would know how to debug, i would do it... :grey_question: 
<img width="512" alt="fbpy" src="https://cloud.githubusercontent.com/assets/5937811/17220388/4961506a-54ef-11e6-9b4a-90727e4b5fb4.png">

**Comment by chidea** [comment]
5 Hours..!
I've never gone so far with my own program yet..
Maybe it's time to add a verbose mode.
Let me test it before that..

**Comment by ozett** [comment]
i saw it dying again after such a timespan.
the first-version i had running for days...

i will wait for a verbose/debugging mode..
maybe it is a memory-error? so the debug-option should show/check for vanishing memory/ram?
dont know pyhton that much, only a guess into the blue...

**Comment by chidea** [comment]
There's not so much things that can be wrong with memory leaking here..
Found "Getotet" in the end of line while reading that screen shot, but there's nothing like that in my code. Where would it come from?
Besides, because there aren't any error message, it looks like just a normal end of program.
It may working as if `-nl` flag have set.
Can you try with this flag on and check if it gives the same playtime?

**Comment by chidea** [comment]
Oh.. I found this bug before but didn't leave note somewhere and forgot.. I'm so sorry.
This bug makes it doesn't loop when shuffle is on. I'll fix it right now.

**Comment by chidea** [comment]
Hmm.. Tested around and found that the only bug case was when it's set to `-nl -sf`.
Still the problem is a mystery..

**Comment by ozett** [comment]
i think i always wanted it looping.
may  i forget to say this on command line, but i dont think i explicitly said -nl and shuffle.
so, from my memory, i would say, the thread died somehow without this two switches.
but i will see how fast i can check against this information from you, if i can reproduce something like 'this' as a bug ..
i will report back.

**Comment by ozett** [comment]
sorry for the delay, i had been on vacation.
recent github-version now running..see how it goes with the old errors.
i will report

**Comment by ozett** [comment]
my task died after around 3-4 hrs.

i have seen a message from my socat-task, where i have a socket on wich i send cmds to the raspberry.
with the cmd i overlay some rtsp-streams with omxplayer onto the picture-frame. this happens for around 5minutes on motion detection.

my guess is now, that fb.py is killed on memory-problems on the framebuffer. somehow.
could this happen this way? can i debug frambuffer memory-consumption?

a screenshot:
<img width="643" alt="layer-memory" src="https://cloud.githubusercontent.com/assets/5937811/17643126/8c4672ca-6160-11e6-8d30-89e3a4b991f8.png">

**Comment by ozett** [comment]
now running for 7hrs +
(can measure while running. but what to do if it is killed somehow?...)

<img width="559" alt="time" src="https://cloud.githubusercontent.com/assets/5937811/17645097/7280fdb6-619b-11e6-926b-3944b459e971.png">

**Comment by ozett** [comment]
next testing i use "/usr/bin/time" from package "time" to measure runtime ->

<img width="512" alt="time2" src="https://cloud.githubusercontent.com/assets/5937811/17645116/1edb0d4a-619c-11e6-9f14-f47d2e809bd6.png">

**Comment by ozett** [comment]
11 hrs runtime, than memory error...  :tada: 

i think my errors must have something to do with framebuffer-memory/gpu-memory or the like.
i have 3-4 times a day the omxplayer starting for 10 sek. to show my rtsp-stream from the webcam.
after 7-11hrs the python fb.py is dead. 
dont know how to debug this. maybe you have a hint?

<img width="821" alt="11" src="https://cloud.githubusercontent.com/assets/5937811/17660957/68546d22-62dc-11e6-9715-239e9b18388a.png">

<img width="512" alt="12" src="https://cloud.githubusercontent.com/assets/5937811/17660963/6e9b6424-62dc-11e6-89db-01a7b0d1f2b8.png">

**Comment by ozett** [comment]
maybe with this:
https://www.hskupin.info/2010/06/17/how-to-fix-the-oom-killer-crashe-under-linux/

--update:
i changed this on my rasperry an have fb.py running..
 lets see how it goes, what runtime we can reach..
:open_mouth:

**Comment by ozett** [comment]
i also found a bug in my script, which started the omxplayer too often (3times) on motion.
now i corrected the check, if the omxplayer is already running (need it only one time :grin: ),
have the settings for vm-memory from the above post active, 
and we will see what runtime fb.py can reach...

**Comment by ozett** [comment]
3:48 hrs... than the end without recognisable reason... :question: 

this time, no dmesg, no hint for memory-errors (in linux :exclamation: )
..i can see nothing special...besides a memory-error in python..

but what to do about? change the parameters of vm-memory back?

<img width="581" alt="elapsed" src="https://cloud.githubusercontent.com/assets/5937811/17670113/b88db2f6-6310-11e6-8913-a37c00065cfd.png">

**Comment by chidea** [comment]
There's an added option `-vb` to print verbose messages.
But there aren't any more thing to print other than just path of playing files..
I guess it needs to be tested with Heapy or memory_profiler.
http://stackoverflow.com/questions/110259/which-python-memory-profiler-is-recommended

**Comment by ozett** [comment]
i will look this up, 
big thanks for this veeeery quick reply
:+1:

**Comment by ozett** [comment]
i followed the link and found at the first glimpse,
that it must be used in the source-code...
:cry:

**Comment by chidea** [comment]
You can also do this with python REPL.
I'll try with mine but I have only 4 gifs to test.

**Comment by ozett** [comment]
> python REPL.
> :question: 

i will look this up. still i am no developer :cry: 

do you want some testing-gifs? 100mb? :laughing: 

hope i can be helpful here, as i love this python-code. 
since i discovered it, it runs all the day on my picture-frame when i am at home..

**Comment by chidea** [comment]
Since it can because of the file you're trying to play, sending the files you played to me isn't a bad idea.

**Comment by ozett** [comment]
as there were a status, which file is currently on display, i could narrow that down.
but i have no prob to send the whole bunch to you, since everthing comes from the net.
preferred upload-service for this? (i found 1,2 GB...) :blush:

**Comment by ozett** [comment]
there are some utils-files in the picture dirs,
i see how i can pack this up like it is on my sdcard

**Comment by ozett** [comment]
i checked this
http://www.howtogeek.com/133761/the-best-free-programs-and-online-services-for-sending-and-sharing-large-files/
and this
http://www.hongkiat.com/blog/file-sharing-tools/
and amazon S3 easy file....

but actually i upload the 900MB up to google drive and send you the link via personal email.
ok?

**Comment by chidea** [comment]
Well I have my own ftp server too.. but google drive is ok.

**Comment by ozett** [comment]
i can send directly to ftp, if you like. with anonymous credentials?
or i send the link to your personal mailadress (wich one?), valid for 12 hrs?
ok?

i reset the vm-memory settings to default on raspberry and had runtime of 2:48 hrs...
<img width="585" alt="error" src="https://cloud.githubusercontent.com/assets/5937811/17678867/35651abc-6339-11e6-85fc-ef712cc5426f.png">

memory error:
<img width="865" alt="error2" src="https://cloud.githubusercontent.com/assets/5937811/17678899/5fd219b2-6339-11e6-9da3-1b09d691d107.png">

**Comment by chidea** [comment]
Email will be easier. That makes it quiet more suspicious on an incorrect file..

**Comment by ozett** [comment]
i tried this:
http://www.eremedia.com/sourcecon/how-to-find-almost-any-github-users-email-address/
and found an google-email. i send to this a pm with dwnld-link for the samples.
ok?

**Comment by chidea** [comment]
Yes it's correct. I got this mail.

**Comment by ozett** [comment]
ok. download ok?
i think i will wait now for you, if you can experience/debug the same memory problems with the python intepreter as i had. ok?

**Comment by ozett** [comment]
13hrs...WOW...still running.. :astonished: 
<img width="689" alt="13hrs" src="https://cloud.githubusercontent.com/assets/5937811/17695622/b92e12fc-63a9-11e6-8e8e-527004f8f58e.png">

**Comment by chidea** [comment]
Yes it's being downloaded.
I'll test it and post the result.

**Comment by chidea** [comment]
Could you try `sudo python3 /usr/src/FBpyGIF/main.py -sf -gd 60 /home/pi/Pictures -vb` and see what's the last played file if it stops on next time?

**Comment by ozett** [comment]
ok. i'll do. i give up my running record of 15:32 and check in for the next...
<img width="490" alt="15" src="https://cloud.githubusercontent.com/assets/5937811/17698653/a54a49fa-63bc-11e6-94f9-6a39a38e56d0.png">

**Comment by ozett** [comment]
last image before exit from program in screenshot.
only 1:48 hrs...
hope you can now check against this specific image.
if it is not a runtime-over-all-error...??

<img width="613" alt="138" src="https://cloud.githubusercontent.com/assets/5937811/17716275/49df63a6-6408-11e6-8c6c-b94a8e448464.png">

**Comment by ozett** [comment]
<img width="512" alt="dmesg" src="https://cloud.githubusercontent.com/assets/5937811/17716304/6c09e64a-6408-11e6-8051-872333827005.png">

**Comment by chidea** [comment]
Yes, thanks. My next guess is that that specific file is large enough than the available memory when it's uncompressed.
There should be a procedure to check available memory and do separation on frames to chunk down to below available size.
Does `sudo python3 /usr/src/FBpyGIF/main.py -gd 60 /home/pi/Pictures/fo46.design17.pictureframe/tumblr_ma9h9eQWHb1qc0s10o1_500.gif` under same memory configuration gets same memory error to you?

**Comment by chidea** [comment]
The same attemption makes endless computation and do nothing but quit on my pi.
I'll focus on fixing with this file.

**Comment by chidea** [comment]
So, the file has 157 frames and it can be easily expected to explode the memory when every frame is uncompressed onto.

**Comment by chidea** [comment]
70c475a10cee79e478ae4dd17e38783c122c9e38 can play this file by cutting out exceed frames.
It's a very trivial way to do this though, works anyway.

**Comment by ozett** [comment]
i will check out the new version and start counting the new max-runtime over all the gif-collection...
thanks for looking into this issue and fixing.
:smile: :smiley:

**Comment by chidea** [comment]
I thank you too for continuous feedbacks.  :)

**Comment by ozett** [comment]
as i am back from holiday, i want to show the pictures on my picture frames.
each in each correct orientation.

i have some ideas, to show the pictures in some sort of "playlist", while changing them to the normal "wallpaper playlist" on certain conditions.

your python-work is the best solution to realize this, and you provided super code-solution.
means. i will continue to provide feedback..
:smiling_imp:  :+1:

**Comment by ozett** [comment]
i now see the change with -vb

<img width="809" alt="big" src="https://cloud.githubusercontent.com/assets/5937811/17734482/bf80b06e-647c-11e6-836b-7e4cb09fc453.png">

**Comment by ozett** [comment]
WOW :astonished:  :tada: 
looks now "rock-solid"... :smile: 

over 1 day ...

<img width="381" alt="runtime" src="https://cloud.githubusercontent.com/assets/5937811/17766300/c6b4e130-652a-11e6-8282-5e7a2dbd950f.png">
