### ISSUE TITLE
Improvement: Help-text with example for RGB-switch

### ISSUE THREAD

**Issue by ozett** [chidea/FBpyGIF#7]
i do this all as a noob, to see if it is self-explanatory.
maybe i could be a help for others, if the help-text of the RGB-switch could show an example?
an expample for Red-Green-Blue Values with valid-scope?

look at my errors, may this explains what i mean...
<img width="542" alt="fbpy-clear" src="https://cloud.githubusercontent.com/assets/5937811/17642313/6a0707da-6140-11e6-9f96-7140f7b9d479.png">

**Comment by chidea** [comment]
It's very standard way..
You can use any color pickers to get this value.
Here's one for example.
http://www.w3schools.com/colors/colors_picker.asp
Choose any color and use that `#ff0000` code without the sharp, result in `-c ff0000`.
That "RGB code" in help meant this.. OK I'll add some examples.

**Comment by chidea** [comment]
be885d70e0e342ba365ac5a0a2ac0bae8f99a54a is for color code exmple.
