### ISSUE TITLE
Improvement: calling main.py without arguments can display help/hint for -help

### ISSUE THREAD

**Issue by ozett** [chidea/FBpyGIF#8]
calling main.py presumes, that you call python3 in front.
(i learned this times ago in the beginning).

now when i call main.py without arguments, i dont see a hint for help.
it is on github mentioned, but i does not come out of the script.

maybe helpful to display a notice on comandline, that help comes from calling main.py -h  ?

<img width="591" alt="mainpy" src="https://cloud.githubusercontent.com/assets/5937811/17642327/151dd9d2-6141-11e6-9705-d94d778cdea5.png">

**Comment by chidea** [comment]
Oops, my bad. One line should be omitted.
f5e2277c861c8af161ac86287f6cba1e47a3faaf will do the work.

**Comment by ozett** [comment]
:+1:
